d

diff --git a/.github/workflows/documentation.yml b/.github/workflows/documentation.yml
--- a/.github/workflows/documentation.yml
+++ b/.github/workflows/documentation.yml
@@ -45,29 +45,29 @@ jobs:
       echo "--- Listing current directory ---"
       ls -la
 
-   - name: Ensure documentation is in the correct location
-     run: |
-      if [ -d "html" ]; then
-        mkdir -p Docs
-        # move the generated HTML files to the Docs directory
-        mv html/* Docs/ || true # Use || true to prevent failure if no non-hidden files
-        mv html/.[!.]* Docs/ || true # Move hidden files, excluding . and ..
-        mv html/..?* Docs/ || true # Move hidden files starting with two dots, excluding ..
+   #  - name: Ensure documentation is in the correct location
+   #    run: |
+   #     if [ -d "html" ]; then
+   #       mkdir -p Docs
+   #       # move the generated HTML files to the Docs directory
+   #       mv html/* Docs/ || true # Use || true to prevent failure if no non-hidden files
+   #       mv html/.[!.]* Docs/ || true # Move hidden files, excluding . and ..
+   #       mv html/..?* Docs/ || true # Move hidden files starting with two dots, excluding ..
 
-        echo "Listing Docs directory after move:"
-        ls -Rla Docs
-        if [ -f "Docs/index.html" ]; then
-          echo "index.html found in Docs"
-        else
-          echo "Error: index.html not found in Docs"
-          exit 1
-        fi
-        echo "Checking for class files in Docs:"
-        find Docs -name "class_*.html" || echo "No class files found in Docs"
-      else
-        echo "Error: html directory not found"
-        exit 1
-      fi
+   #       echo "Listing Docs directory after move:"
+   #       ls -Rla Docs
+   #       if [ -f "Docs/index.html" ]; then
+   #         echo "index.html found in Docs"
+   #       else
+   #         echo "Error: index.html not found in Docs"
+   #         exit 1
+   #       fi
+   #       echo "Checking for class files in Docs:"
+   #       find Docs -name "class_*.html" || echo "No class files found in Docs"
+   #     else
+   #       echo "Error: html directory not found"
+   #       exit 1
+   #     fi
 
    - name: List artifact files before upload
      run: |
